### ISSUE TITLE
自定义的代码片段太长 detail 需要支持语法高亮

### ISSUE THREAD

**Issue by d1y** [d1y/scls#7]
示例配置:

```toml
[[snippets]]
prefix = "ff"
scope = [ "cpp" ]
body = "#include ‹iostream>\n\nusing namespace std; \n\ntry {\n\t$1\n} catch (const exception& err) {\n\tcerr « err-what() < endl;\n\t$2\n}"
```
<img width="764" alt="image" src="https://github.com/d1y/scls/assets/45585937/f0f576fb-e404-44fc-a00b-875ed0c739a3">
